[package]
name = "comics_archive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.10", features = ["derive"] }
indicatif = "0.17.1"
walkdir = "2.3.2"
zip = "0.6.2"
